// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lionheart.Data;

#nullable disable

namespace lionheart.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20250801040046_ChatConversation")]
    partial class ChatConversation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ChatConversation", b =>
                {
                    b.Property<Guid>("ChatConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatConversationId");

                    b.HasIndex("UserID");

                    b.ToTable("ChatConversations");
                });

            modelBuilder.Entity("ChatMessageItem", b =>
                {
                    b.Property<Guid>("ChatMessageItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatConversationID")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatMessageRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatMessageItemID");

                    b.HasIndex("ChatConversationID");

                    b.ToTable("ChatMessageItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("lionheart.ActivityTracking.Activity", b =>
                {
                    b.Property<Guid>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccumulatedFatigue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DifficultyRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EngagementRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExternalVariablesRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityID");

                    b.HasIndex("UserID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("lionheart.ActivityTracking.LiftDetails", b =>
                {
                    b.Property<Guid>("ActivityID")
                        .HasColumnType("TEXT");

                    b.Property<int>("BackSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BicepSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChestSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HamstringSets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LiftFocus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LiftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuadSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShoulderSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tonnage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TricepSets")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivityID");

                    b.ToTable("LiftDetails");
                });

            modelBuilder.Entity("lionheart.ActivityTracking.RideDetails", b =>
                {
                    b.Property<Guid>("ActivityID")
                        .HasColumnType("TEXT");

                    b.Property<int>("AveragePower")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int>("ElevationGain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RideType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityID");

                    b.ToTable("RideDetails");
                });

            modelBuilder.Entity("lionheart.ActivityTracking.RunWalkDetails", b =>
                {
                    b.Property<Guid>("ActivityID")
                        .HasColumnType("TEXT");

                    b.Property<int>("AveragePaceInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int>("ElevationGain")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("MileSplitsInSeconds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityID");

                    b.ToTable("RunWalkDetails");
                });

            modelBuilder.Entity("lionheart.Model.Injury.Injury", b =>
                {
                    b.Property<Guid>("InjuryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InjuryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("InjuryID");

                    b.HasIndex("UserID");

                    b.ToTable("Injuries");
                });

            modelBuilder.Entity("lionheart.Model.Injury.InjuryEvent", b =>
                {
                    b.Property<Guid>("InjuryEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InjuryID")
                        .HasColumnType("TEXT");

                    b.Property<int>("InjuryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PainLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrainingSessionID")
                        .HasColumnType("TEXT");

                    b.HasKey("InjuryEventID");

                    b.HasIndex("InjuryID");

                    b.ToTable("InjuryEvents");
                });

            modelBuilder.Entity("lionheart.Model.Oura.DailyOuraInfo", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadinessJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResilienceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SleepJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SyncDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ObjectID");

                    b.HasIndex("UserID");

                    b.ToTable("DailyOuraInfos");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.Equipment", b =>
                {
                    b.Property<Guid>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("EquipmentID");

                    b.HasIndex("UserID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.Movement", b =>
                {
                    b.Property<Guid>("MovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MovementBaseID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrainingSessionID")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightUnit")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovementID");

                    b.HasIndex("MovementBaseID");

                    b.HasIndex("TrainingSessionID");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.MovementBase", b =>
                {
                    b.Property<Guid>("MovementBaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("MovementBaseID");

                    b.HasIndex("UserID");

                    b.ToTable("MovementBases");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.SetEntry", b =>
                {
                    b.Property<Guid>("SetEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ActualRPE")
                        .HasColumnType("REAL");

                    b.Property<int>("ActualReps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualWeight")
                        .HasColumnType("REAL");

                    b.Property<Guid>("MovementID")
                        .HasColumnType("TEXT");

                    b.Property<double>("RecommendedRPE")
                        .HasColumnType("REAL");

                    b.Property<int>("RecommendedReps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RecommendedWeight")
                        .HasColumnType("REAL");

                    b.HasKey("SetEntryID");

                    b.HasIndex("MovementID");

                    b.ToTable("SetEntries");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.TrainingProgram", b =>
                {
                    b.Property<Guid>("TrainingProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("NextTrainingSessionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("TrainingProgramID");

                    b.HasIndex("UserID");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.TrainingSession", b =>
                {
                    b.Property<Guid>("TrainingSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrainingProgramID")
                        .HasColumnType("TEXT");

                    b.HasKey("TrainingSessionID");

                    b.HasIndex("TrainingProgramID");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("lionheart.WellBeing.ApiAccessToken", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ObjectID");

                    b.HasIndex("UserID");

                    b.ToTable("ApiAccessTokens");
                });

            modelBuilder.Entity("lionheart.WellBeing.LionheartUser", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("UserID");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("LionheartUsers");
                });

            modelBuilder.Entity("lionheart.WellBeing.WellnessState", b =>
                {
                    b.Property<Guid>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnergyScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoodScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotivationScore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OverallScore")
                        .HasColumnType("REAL");

                    b.Property<int>("StressScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("StateID");

                    b.HasIndex("UserID");

                    b.ToTable("WellnessStates");
                });

            modelBuilder.Entity("ChatConversation", b =>
                {
                    b.HasOne("lionheart.WellBeing.LionheartUser", null)
                        .WithMany("ChatConversations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatMessageItem", b =>
                {
                    b.HasOne("ChatConversation", "ChatConversation")
                        .WithMany("Messages")
                        .HasForeignKey("ChatConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatConversation");
                });

            modelBuilder.Entity("lionheart.ActivityTracking.Activity", b =>
                {
                    b.HasOne("lionheart.WellBeing.LionheartUser", null)
                        .WithMany("Activities")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.ActivityTracking.LiftDetails", b =>
                {
                    b.HasOne("lionheart.ActivityTracking.Activity", null)
                        .WithOne("LiftDetails")
                        .HasForeignKey("lionheart.ActivityTracking.LiftDetails", "ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.ActivityTracking.RideDetails", b =>
                {
                    b.HasOne("lionheart.ActivityTracking.Activity", null)
                        .WithOne("RideDetails")
                        .HasForeignKey("lionheart.ActivityTracking.RideDetails", "ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.ActivityTracking.RunWalkDetails", b =>
                {
                    b.HasOne("lionheart.ActivityTracking.Activity", null)
                        .WithOne("RunWalkDetails")
                        .HasForeignKey("lionheart.ActivityTracking.RunWalkDetails", "ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.Injury.Injury", b =>
                {
                    b.HasOne("lionheart.WellBeing.LionheartUser", null)
                        .WithMany("Injuries")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.Injury.InjuryEvent", b =>
                {
                    b.HasOne("lionheart.Model.Injury.Injury", "Injury")
                        .WithMany("InjuryEvents")
                        .HasForeignKey("InjuryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Injury");
                });

            modelBuilder.Entity("lionheart.Model.Oura.DailyOuraInfo", b =>
                {
                    b.HasOne("lionheart.WellBeing.LionheartUser", null)
                        .WithMany("DailyOuraInfos")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("lionheart.Model.Oura.ActivityData", "ActivityData", b1 =>
                        {
                            b1.Property<Guid>("DailyOuraInfoObjectID")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ActiveCalories")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ActivityScore")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MeetDailyTargets")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MoveEveryHour")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("RecoveryTime")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("StayActive")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Steps")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TargetCalories")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TotalCalories")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TrainingFrequency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TrainingVolume")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DailyOuraInfoObjectID");

                            b1.ToTable("DailyOuraInfos");

                            b1.WithOwner()
                                .HasForeignKey("DailyOuraInfoObjectID");
                        });

                    b.OwnsOne("lionheart.Model.Oura.ReadinessData", "ReadinessData", b1 =>
                        {
                            b1.Property<Guid>("DailyOuraInfoObjectID")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ActivityBalance")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BodyTemperature")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("HrvBalance")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PreviousDayActivity")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PreviousNight")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReadinessScore")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("RecoveryIndex")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("RestingHeartRate")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SleepBalance")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("TemperatureDeviation")
                                .HasColumnType("REAL");

                            b1.HasKey("DailyOuraInfoObjectID");

                            b1.ToTable("DailyOuraInfos");

                            b1.WithOwner()
                                .HasForeignKey("DailyOuraInfoObjectID");
                        });

                    b.OwnsOne("lionheart.Model.Oura.ResilienceData", "ResilienceData", b1 =>
                        {
                            b1.Property<Guid>("DailyOuraInfoObjectID")
                                .HasColumnType("TEXT");

                            b1.Property<double>("DaytimeRecovery")
                                .HasColumnType("REAL");

                            b1.Property<string>("ResilienceLevel")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double>("SleepRecovery")
                                .HasColumnType("REAL");

                            b1.Property<double>("Stress")
                                .HasColumnType("REAL");

                            b1.HasKey("DailyOuraInfoObjectID");

                            b1.ToTable("DailyOuraInfos");

                            b1.WithOwner()
                                .HasForeignKey("DailyOuraInfoObjectID");
                        });

                    b.OwnsOne("lionheart.Model.Oura.SleepData", "SleepData", b1 =>
                        {
                            b1.Property<Guid>("DailyOuraInfoObjectID")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DeepSleep")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Efficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Latency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("RemSleep")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Restfulness")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SleepScore")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Timing")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TotalSleep")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DailyOuraInfoObjectID");

                            b1.ToTable("DailyOuraInfos");

                            b1.WithOwner()
                                .HasForeignKey("DailyOuraInfoObjectID");
                        });

                    b.Navigation("ActivityData")
                        .IsRequired();

                    b.Navigation("ReadinessData")
                        .IsRequired();

                    b.Navigation("ResilienceData")
                        .IsRequired();

                    b.Navigation("SleepData")
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.Equipment", b =>
                {
                    b.HasOne("lionheart.WellBeing.LionheartUser", null)
                        .WithMany("Equipments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.Movement", b =>
                {
                    b.HasOne("lionheart.Model.TrainingProgram.MovementBase", "MovementBase")
                        .WithMany()
                        .HasForeignKey("MovementBaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lionheart.Model.TrainingProgram.TrainingSession", "TrainingSession")
                        .WithMany("Movements")
                        .HasForeignKey("TrainingSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("lionheart.Model.TrainingProgram.MovementModifier", "MovementModifier", b1 =>
                        {
                            b1.Property<Guid>("MovementID")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Duration")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("EquipmentID")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("MovementID");

                            b1.HasIndex("EquipmentID");

                            b1.ToTable("Movements");

                            b1.HasOne("lionheart.Model.TrainingProgram.Equipment", "Equipment")
                                .WithMany()
                                .HasForeignKey("EquipmentID")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("MovementID");

                            b1.Navigation("Equipment");
                        });

                    b.Navigation("MovementBase");

                    b.Navigation("MovementModifier")
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.MovementBase", b =>
                {
                    b.HasOne("lionheart.WellBeing.LionheartUser", null)
                        .WithMany("MovementBases")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.SetEntry", b =>
                {
                    b.HasOne("lionheart.Model.TrainingProgram.Movement", "Movement")
                        .WithMany("Sets")
                        .HasForeignKey("MovementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.TrainingProgram", b =>
                {
                    b.HasOne("lionheart.WellBeing.LionheartUser", null)
                        .WithMany("TrainingPrograms")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.TrainingSession", b =>
                {
                    b.HasOne("lionheart.Model.TrainingProgram.TrainingProgram", "TrainingProgram")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("lionheart.WellBeing.ApiAccessToken", b =>
                {
                    b.HasOne("lionheart.WellBeing.LionheartUser", null)
                        .WithMany("ApiAccessTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.WellBeing.LionheartUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("lionheart.WellBeing.WellnessState", b =>
                {
                    b.HasOne("lionheart.WellBeing.LionheartUser", null)
                        .WithMany("WellnessStates")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("lionheart.ActivityTracking.Activity", b =>
                {
                    b.Navigation("LiftDetails");

                    b.Navigation("RideDetails");

                    b.Navigation("RunWalkDetails");
                });

            modelBuilder.Entity("lionheart.Model.Injury.Injury", b =>
                {
                    b.Navigation("InjuryEvents");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.Movement", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.TrainingProgram", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("lionheart.Model.TrainingProgram.TrainingSession", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("lionheart.WellBeing.LionheartUser", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ApiAccessTokens");

                    b.Navigation("ChatConversations");

                    b.Navigation("DailyOuraInfos");

                    b.Navigation("Equipments");

                    b.Navigation("Injuries");

                    b.Navigation("MovementBases");

                    b.Navigation("TrainingPrograms");

                    b.Navigation("WellnessStates");
                });
#pragma warning restore 612, 618
        }
    }
}
