// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lionheart.Data;

#nullable disable

namespace lionheart.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20260125041622_MuscleGroups")]
    partial class MuscleGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("MovementBase", b =>
                {
                    b.Property<Guid>("MovementBaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("MovementBaseID");

                    b.HasIndex("UserID");

                    b.ToTable("MovementBases");
                });

            modelBuilder.Entity("MuscleGroup", b =>
                {
                    b.Property<Guid>("MuscleGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MovementBaseID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MuscleGroupID");

                    b.HasIndex("MovementBaseID");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("OpenAI.Chat.ChatToolCall", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LHModelChatMessageChatMessageItemID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LHModelChatMessageChatMessageItemID");

                    b.ToTable("ChatToolCall");
                });

            modelBuilder.Entity("lionheart.ActivityTracking.Activity", b =>
                {
                    b.Property<Guid>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityID");

                    b.HasIndex("UserID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHChatConversation", b =>
                {
                    b.Property<Guid>("ChatConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LionheartUserUserID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatConversationID");

                    b.HasIndex("LionheartUserUserID");

                    b.ToTable("ChatConversations");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHModelChatMessage", b =>
                {
                    b.Property<Guid>("ChatMessageItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatConversationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatMessageItemID");

                    b.HasIndex("ChatConversationID");

                    b.ToTable("ModelChatMessages");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHSystemChatMessage", b =>
                {
                    b.Property<Guid>("ChatMessageItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatConversationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatMessageItemID");

                    b.HasIndex("ChatConversationID")
                        .IsUnique();

                    b.ToTable("SystemChatMessages");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHToolChatMessage", b =>
                {
                    b.Property<Guid>("ChatMessageItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatConversationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolCallID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChatMessageItemID");

                    b.HasIndex("ChatConversationID");

                    b.ToTable("ToolChatMessages");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHUserChatMessage", b =>
                {
                    b.Property<Guid>("ChatMessageItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatConversationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatMessageItemID");

                    b.HasIndex("ChatConversationID");

                    b.ToTable("UserChatMessages");
                });

            modelBuilder.Entity("lionheart.Model.InjuryManagement.Injury", b =>
                {
                    b.Property<Guid>("InjuryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InjuryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("InjuryID");

                    b.HasIndex("UserID");

                    b.ToTable("Injuries");
                });

            modelBuilder.Entity("lionheart.Model.InjuryManagement.InjuryEvent", b =>
                {
                    b.Property<Guid>("InjuryEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InjuryID")
                        .HasColumnType("TEXT");

                    b.Property<int>("InjuryType")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("MovementIDs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PainLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TrainingSessionID")
                        .HasColumnType("TEXT");

                    b.HasKey("InjuryEventID");

                    b.HasIndex("InjuryID");

                    b.ToTable("InjuryEvents");
                });

            modelBuilder.Entity("lionheart.Model.Oura.DailyOuraData", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadinessJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResilienceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SleepJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SyncDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ObjectID");

                    b.HasIndex("UserID");

                    b.ToTable("DailyOuraDatas");
                });

            modelBuilder.Entity("lionheart.Model.Training.Equipment", b =>
                {
                    b.Property<Guid>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("EquipmentID");

                    b.HasIndex("UserID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("lionheart.Model.Training.Movement", b =>
                {
                    b.Property<Guid>("MovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MovementDataID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrainingSessionID")
                        .HasColumnType("TEXT");

                    b.HasKey("MovementID");

                    b.HasIndex("MovementDataID");

                    b.HasIndex("TrainingSessionID");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("lionheart.Model.Training.MovementData", b =>
                {
                    b.Property<Guid>("MovementDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipmentID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovementBaseID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MovementModifierID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("MovementDataID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("MovementBaseID");

                    b.HasIndex("MovementModifierID");

                    b.HasIndex("UserID", "EquipmentID", "MovementBaseID", "MovementModifierID")
                        .IsUnique();

                    b.ToTable("MovementDatas");
                });

            modelBuilder.Entity("lionheart.Model.Training.MovementModifier", b =>
                {
                    b.Property<Guid>("MovementModifierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("MovementModifierID");

                    b.HasIndex("UserID");

                    b.ToTable("MovementModifiers");
                });

            modelBuilder.Entity("lionheart.Model.Training.PersonalRecord", b =>
                {
                    b.Property<Guid>("PersonalRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MovementDataID")
                        .HasColumnType("TEXT");

                    b.Property<int>("PRType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PreviousPRCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousPersonalRecordID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceLiftSetEntryID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WeightUnit")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonalRecordID");

                    b.HasIndex("MovementDataID");

                    b.HasIndex("PreviousPersonalRecordID");

                    b.HasIndex("SourceLiftSetEntryID");

                    b.HasIndex("UserID", "MovementDataID", "PRType", "IsActive");

                    b.ToTable("PersonalRecords");
                });

            modelBuilder.Entity("lionheart.Model.Training.SetEntry.DTSetEntry", b =>
                {
                    b.Property<Guid>("SetEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ActualDistance")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("ActualDuration")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ActualPace")
                        .HasColumnType("TEXT");

                    b.Property<double>("ActualRPE")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("ActualRest")
                        .HasColumnType("TEXT");

                    b.Property<int>("DistanceUnit")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("IntervalDuration")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MovementID")
                        .HasColumnType("TEXT");

                    b.Property<double>("RecommendedDistance")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("RecommendedDuration")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("RecommendedRest")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TargetPace")
                        .HasColumnType("TEXT");

                    b.HasKey("SetEntryID");

                    b.HasIndex("MovementID");

                    b.ToTable("DTSetEntries");
                });

            modelBuilder.Entity("lionheart.Model.Training.SetEntry.LiftSetEntry", b =>
                {
                    b.Property<Guid>("SetEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ActualRPE")
                        .HasColumnType("REAL");

                    b.Property<int>("ActualReps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualWeight")
                        .HasColumnType("REAL");

                    b.Property<Guid>("MovementID")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RecommendedRPE")
                        .HasColumnType("REAL");

                    b.Property<int?>("RecommendedReps")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RecommendedWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("WeightUnit")
                        .HasColumnType("INTEGER");

                    b.HasKey("SetEntryID");

                    b.HasIndex("MovementID");

                    b.ToTable("LiftSetEntries");
                });

            modelBuilder.Entity("lionheart.Model.Training.TrainingProgram", b =>
                {
                    b.Property<Guid>("TrainingProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("TrainingProgramID");

                    b.HasIndex("UserID");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("lionheart.Model.Training.TrainingSession", b =>
                {
                    b.Property<Guid>("TrainingSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TrainingProgramID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("TrainingSessionID");

                    b.HasIndex("TrainingProgramID");

                    b.HasIndex("UserID");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("lionheart.Model.User.ApiAccessToken", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ObjectID");

                    b.HasIndex("UserID");

                    b.ToTable("ApiAccessTokens");
                });

            modelBuilder.Entity("lionheart.Model.User.LionheartUser", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("UserID");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("LionheartUsers");
                });

            modelBuilder.Entity("lionheart.WellBeing.WellnessState", b =>
                {
                    b.Property<Guid>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnergyScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoodScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotivationScore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OverallScore")
                        .HasColumnType("REAL");

                    b.Property<int>("StressScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("StateID");

                    b.HasIndex("UserID");

                    b.ToTable("WellnessStates");
                });

            modelBuilder.Entity("MovementBase", b =>
                {
                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("MovementBases")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuscleGroup", b =>
                {
                    b.HasOne("MovementBase", null)
                        .WithMany("MuscleGroups")
                        .HasForeignKey("MovementBaseID");
                });

            modelBuilder.Entity("OpenAI.Chat.ChatToolCall", b =>
                {
                    b.HasOne("lionheart.Model.Chat.LHModelChatMessage", null)
                        .WithMany("ToolCalls")
                        .HasForeignKey("LHModelChatMessageChatMessageItemID");
                });

            modelBuilder.Entity("lionheart.ActivityTracking.Activity", b =>
                {
                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("Activities")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PerceivedEffortRatings", "PerceivedEffortRatings", b1 =>
                        {
                            b1.Property<Guid>("ActivityID")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("AccumulatedFatigue")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("DifficultyRating")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("EngagementRating")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("ExternalVariablesRating")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("TEXT");

                            b1.HasKey("ActivityID");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityID");
                        });

                    b.Navigation("PerceivedEffortRatings");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHChatConversation", b =>
                {
                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("ChatConversations")
                        .HasForeignKey("LionheartUserUserID");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHModelChatMessage", b =>
                {
                    b.HasOne("lionheart.Model.Chat.LHChatConversation", "ChatConversation")
                        .WithMany("ModelMessages")
                        .HasForeignKey("ChatConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatConversation");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHSystemChatMessage", b =>
                {
                    b.HasOne("lionheart.Model.Chat.LHChatConversation", "ChatConversation")
                        .WithOne("ChatSystemMessage")
                        .HasForeignKey("lionheart.Model.Chat.LHSystemChatMessage", "ChatConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatConversation");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHToolChatMessage", b =>
                {
                    b.HasOne("lionheart.Model.Chat.LHChatConversation", "ChatConversation")
                        .WithMany("ToolMessages")
                        .HasForeignKey("ChatConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatConversation");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHUserChatMessage", b =>
                {
                    b.HasOne("lionheart.Model.Chat.LHChatConversation", "ChatConversation")
                        .WithMany("UserMessages")
                        .HasForeignKey("ChatConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatConversation");
                });

            modelBuilder.Entity("lionheart.Model.InjuryManagement.Injury", b =>
                {
                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("Injuries")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.InjuryManagement.InjuryEvent", b =>
                {
                    b.HasOne("lionheart.Model.InjuryManagement.Injury", "Injury")
                        .WithMany("InjuryEvents")
                        .HasForeignKey("InjuryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Injury");
                });

            modelBuilder.Entity("lionheart.Model.Oura.DailyOuraData", b =>
                {
                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("DailyOuraInfos")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("lionheart.Model.Oura.ActivityData", "ActivityData", b1 =>
                        {
                            b1.Property<Guid>("DailyOuraDataObjectID")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ActiveCalories")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ActivityScore")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MeetDailyTargets")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MoveEveryHour")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("RecoveryTime")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("StayActive")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Steps")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TargetCalories")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TotalCalories")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TrainingFrequency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TrainingVolume")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DailyOuraDataObjectID");

                            b1.ToTable("DailyOuraDatas");

                            b1.WithOwner()
                                .HasForeignKey("DailyOuraDataObjectID");
                        });

                    b.OwnsOne("lionheart.Model.Oura.ReadinessData", "ReadinessData", b1 =>
                        {
                            b1.Property<Guid>("DailyOuraDataObjectID")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ActivityBalance")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BodyTemperature")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("HrvBalance")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PreviousDayActivity")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PreviousNight")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReadinessScore")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("RecoveryIndex")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("RestingHeartRate")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SleepBalance")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("TemperatureDeviation")
                                .HasColumnType("REAL");

                            b1.HasKey("DailyOuraDataObjectID");

                            b1.ToTable("DailyOuraDatas");

                            b1.WithOwner()
                                .HasForeignKey("DailyOuraDataObjectID");
                        });

                    b.OwnsOne("lionheart.Model.Oura.ResilienceData", "ResilienceData", b1 =>
                        {
                            b1.Property<Guid>("DailyOuraDataObjectID")
                                .HasColumnType("TEXT");

                            b1.Property<double>("DaytimeRecovery")
                                .HasColumnType("REAL");

                            b1.Property<string>("ResilienceLevel")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double>("SleepRecovery")
                                .HasColumnType("REAL");

                            b1.Property<double>("Stress")
                                .HasColumnType("REAL");

                            b1.HasKey("DailyOuraDataObjectID");

                            b1.ToTable("DailyOuraDatas");

                            b1.WithOwner()
                                .HasForeignKey("DailyOuraDataObjectID");
                        });

                    b.OwnsOne("lionheart.Model.Oura.SleepData", "SleepData", b1 =>
                        {
                            b1.Property<Guid>("DailyOuraDataObjectID")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DeepSleep")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Efficiency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Latency")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("RemSleep")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Restfulness")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SleepScore")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Timing")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TotalSleep")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DailyOuraDataObjectID");

                            b1.ToTable("DailyOuraDatas");

                            b1.WithOwner()
                                .HasForeignKey("DailyOuraDataObjectID");
                        });

                    b.Navigation("ActivityData")
                        .IsRequired();

                    b.Navigation("ReadinessData")
                        .IsRequired();

                    b.Navigation("ResilienceData")
                        .IsRequired();

                    b.Navigation("SleepData")
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.Training.Equipment", b =>
                {
                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("Equipments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.Training.Movement", b =>
                {
                    b.HasOne("lionheart.Model.Training.MovementData", "MovementData")
                        .WithMany()
                        .HasForeignKey("MovementDataID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lionheart.Model.Training.TrainingSession", "TrainingSession")
                        .WithMany("Movements")
                        .HasForeignKey("TrainingSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovementData");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("lionheart.Model.Training.MovementData", b =>
                {
                    b.HasOne("lionheart.Model.Training.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovementBase", "MovementBase")
                        .WithMany()
                        .HasForeignKey("MovementBaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lionheart.Model.Training.MovementModifier", "MovementModifier")
                        .WithMany()
                        .HasForeignKey("MovementModifierID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("MovementDatas")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("MovementBase");

                    b.Navigation("MovementModifier");
                });

            modelBuilder.Entity("lionheart.Model.Training.MovementModifier", b =>
                {
                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("MovementModifiers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.Training.PersonalRecord", b =>
                {
                    b.HasOne("lionheart.Model.Training.MovementData", "MovementData")
                        .WithMany()
                        .HasForeignKey("MovementDataID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lionheart.Model.Training.PersonalRecord", "PreviousPersonalRecord")
                        .WithMany()
                        .HasForeignKey("PreviousPersonalRecordID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("lionheart.Model.Training.SetEntry.LiftSetEntry", "SourceLiftSetEntry")
                        .WithMany()
                        .HasForeignKey("SourceLiftSetEntryID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("PersonalRecords")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovementData");

                    b.Navigation("PreviousPersonalRecord");

                    b.Navigation("SourceLiftSetEntry");
                });

            modelBuilder.Entity("lionheart.Model.Training.SetEntry.DTSetEntry", b =>
                {
                    b.HasOne("lionheart.Model.Training.Movement", "Movement")
                        .WithMany("DistanceTimeSets")
                        .HasForeignKey("MovementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("lionheart.Model.Training.SetEntry.LiftSetEntry", b =>
                {
                    b.HasOne("lionheart.Model.Training.Movement", "Movement")
                        .WithMany("LiftSets")
                        .HasForeignKey("MovementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("lionheart.Model.Training.TrainingProgram", b =>
                {
                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("TrainingPrograms")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.Training.TrainingSession", b =>
                {
                    b.HasOne("lionheart.Model.Training.TrainingProgram", "TrainingProgram")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingProgramID");

                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("TrainingSessions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PerceivedEffortRatings", "PerceivedEffortRatings", b1 =>
                        {
                            b1.Property<Guid>("TrainingSessionID")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("AccumulatedFatigue")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("DifficultyRating")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("EngagementRating")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("ExternalVariablesRating")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("TEXT");

                            b1.HasKey("TrainingSessionID");

                            b1.ToTable("TrainingSessions");

                            b1.WithOwner()
                                .HasForeignKey("TrainingSessionID");
                        });

                    b.Navigation("PerceivedEffortRatings");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("lionheart.Model.User.ApiAccessToken", b =>
                {
                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("ApiAccessTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lionheart.Model.User.LionheartUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("lionheart.WellBeing.WellnessState", b =>
                {
                    b.HasOne("lionheart.Model.User.LionheartUser", null)
                        .WithMany("WellnessStates")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovementBase", b =>
                {
                    b.Navigation("MuscleGroups");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHChatConversation", b =>
                {
                    b.Navigation("ChatSystemMessage")
                        .IsRequired();

                    b.Navigation("ModelMessages");

                    b.Navigation("ToolMessages");

                    b.Navigation("UserMessages");
                });

            modelBuilder.Entity("lionheart.Model.Chat.LHModelChatMessage", b =>
                {
                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("lionheart.Model.InjuryManagement.Injury", b =>
                {
                    b.Navigation("InjuryEvents");
                });

            modelBuilder.Entity("lionheart.Model.Training.Movement", b =>
                {
                    b.Navigation("DistanceTimeSets");

                    b.Navigation("LiftSets");
                });

            modelBuilder.Entity("lionheart.Model.Training.TrainingProgram", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("lionheart.Model.Training.TrainingSession", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("lionheart.Model.User.LionheartUser", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ApiAccessTokens");

                    b.Navigation("ChatConversations");

                    b.Navigation("DailyOuraInfos");

                    b.Navigation("Equipments");

                    b.Navigation("Injuries");

                    b.Navigation("MovementBases");

                    b.Navigation("MovementDatas");

                    b.Navigation("MovementModifiers");

                    b.Navigation("PersonalRecords");

                    b.Navigation("TrainingPrograms");

                    b.Navigation("TrainingSessions");

                    b.Navigation("WellnessStates");
                });
#pragma warning restore 612, 618
        }
    }
}
