using NJsonSchema;
using NSwag.CodeGeneration.OperationNameGenerators;

/// <summary>
/// Custom implementation of <see cref="IOperationNameGenerator"/> that generates safe operation names.
/// This generator ensures that operation names are valid identifiers by prefixing them with an underscore if they start with a digit.
/// 
/// Created to solve an issue where ASP.NET Identity API endpoints generated by NSwag included '2fa', which caused issues with the generated TypeScript client.
/// </summary>
public class SafeOperationNameGenerator : IOperationNameGenerator
{
    /// <summary>Gets a value indicating whether the generator supports multiple client classes.</summary>
    public bool SupportsMultipleClients { get; } = true;



    public string GetClientName(NSwag.OpenApiDocument document, string path, string httpMethod, NSwag.OpenApiOperation operation)
    {
        // TODO: Validate whether the '!' is okay here. The MultipleClientsFromFirstTagAndOperationIdGenerator implementation has the same line of code withput the '!' operator.
        // I only added it to avoid a warning about nullability.
        return ConversionUtilities.ConvertToUpperCamelCase(operation.Tags.FirstOrDefault()!, false);
    }



    public string GetOperationName(NSwag.OpenApiDocument document, string path, string httpMethod, NSwag.OpenApiOperation operation)
    {
        // Get the client name to check for conflicts
        var clientName = GetClientName(document, path, httpMethod, operation);
        
        // Count how many operations in this client use the same HTTP method
        var operationsInClient = document.Operations
            .Where(op => GetClientName(document, op.Path, op.Method, op.Operation) == clientName)
            .Count(op => op.Method.Equals(httpMethod, StringComparison.InvariantCultureIgnoreCase));

        // If there's only one operation with this HTTP method in this client, use the method name
        if (operationsInClient == 1)
        {
            return httpMethod.ToLowerInvariant();
        }

        // Otherwise, use the operation ID (with safety check for leading digits)
        var operationName = operation.OperationId;
        if (!string.IsNullOrEmpty(operationName) && char.IsDigit(operationName[0]))
        {
            operationName = "_" + operationName;
        }
        return operationName;
    }
}

